@endpoint = http://localhost:3000
@cognitoEndpoint = http://localhost:9229
@clientId = dnk8y7ii3wled35p3lw0l2cd7
# account's username 
@username = admin2
# account's password
@password = admin1234
# account's email
@email = admin2@example.com

@apiBaseUrl = {{endpoint}}/api
@eventBaseUrl = {{endpoint}}/event

###
GET {{endpoint}} HTTP/1.1

###
# login
# @name login_cognito
POST {{cognitoEndpoint}}
Accept: application/json
Content-Type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth

{
  "AuthFlow": "USER_PASSWORD_AUTH",
  "ClientId": "{{clientId}}",
  "AuthParameters": {
    "USERNAME": "{{username}}",
    "PASSWORD": "{{password}}"
  },
  "ClientMetadata": {}
}

###
@token = {{login_cognito.response.body.AuthenticationResult.IdToken}}
###

# Health
GET {{endpoint}}
Accept: application/json
Authorization: {{token}}

###
GET {{apiBaseUrl}}/todo
Accept: application/json
Content-Type: application/json
Authorization: {{token}}
X-Tenant-Code: MBC


###
GET {{apiBaseUrl}}/todo/TODO%23MBC/01J9R0JPF04A5HPRQ5RR8GGYDY
Accept: application/json
Content-Type: application/json
Authorization: {{token}}
X-Tenant-Code: MBC

###
POST {{apiBaseUrl}}/todo
Accept: application/json
Content-Type: application/json
Authorization: {{token}}
X-Tenant-Code: MBC

{
  "name": "First task",
  "attributes": {
    "description": "Description for the first task"
  }
}

###
PATCH {{apiBaseUrl}}/todo/TODO%23MBC/01J9WJM4W0S5R4KN5MG080KVB4
Accept: application/json
Content-Type: application/json
Authorization: {{token}}
X-Tenant-Code: MBC

{
  "name": "First update",
  "attributes": {
    "status": "COMPLETED"
  }
}

###
DELETE {{apiBaseUrl}}/todo/TODO%23MBC/01J9R0JPF04A5HPRQ5RR8GGYDY
Accept: application/json
Content-Type: application/json
Authorization: {{token}}
X-Tenant-Code: MBC